spring:
  datasource:
    url: jdbc:mysql://120.79.222.252:3306/javashop?allowMultiQueries:true&characterEncoding:UTF-8&zeroDateTimeBehavior:convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 120.79.222.252 # Redis服务器地址 （默认为127.0.0.1）
    port: 6379    # Redis服务器连接端口 （默认为6379）
    password:   # Redis服务器连接密码（默认为空）
    timeout: 2000  # 连接超时时间（毫秒）
  cache:
    type: redis